//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchIn.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF76608A")]
        public global::System.Windows.Media.Color SelectedAccentColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectedAccentColor"]));
            }
            set {
                this["SelectedAccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/PunchIn;component/Assets/Themes/underworld.xaml")]
        public global::System.Uri SelectedThemeSource {
            get {
                return ((global::System.Uri)(this["SelectedThemeSource"]));
            }
            set {
                this["SelectedThemeSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,720,600")]
        public global::System.Windows.Rect MainWindowLocation {
            get {
                return ((global::System.Windows.Rect)(this["MainWindowLocation"]));
            }
            set {
                this["MainWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hin-tfsportal/my/personal/he62276/")]
        public global::System.Uri SharePointSiteUri {
            get {
                return ((global::System.Uri)(this["SharePointSiteUri"]));
            }
            set {
                this["SharePointSiteUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Micro Management")]
        public string SharePointListName {
            get {
                return ((string)(this["SharePointListName"]));
            }
            set {
                this["SharePointListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy.MM.dd hh:mm")]
        public string DefaultDateTimePickerFormatString {
            get {
                return ((string)(this["DefaultDateTimePickerFormatString"]));
            }
            set {
                this["DefaultDateTimePickerFormatString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd/MM/yyyy")]
        public string DefaultDatePickerFormatString {
            get {
                return ((string)(this["DefaultDatePickerFormatString"]));
            }
            set {
                this["DefaultDatePickerFormatString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultUserShortcutFolderLocation {
            get {
                return ((string)(this["DefaultUserShortcutFolderLocation"]));
            }
            set {
                this["DefaultUserShortcutFolderLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultUserDatabaseFolderLocation {
            get {
                return ((string)(this["DefaultUserDatabaseFolderLocation"]));
            }
            set {
                this["DefaultUserDatabaseFolderLocation"] = value;
            }
        }
    }
}
